accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('selvoc/accounts/', include('accounts.urls')),
    path('selvoc/wordbook/', include('wordbook.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserManager(AbstractUser):
    class Meta:
        db_table = 'usermanager'

    user_id = models.AutoField(
        primary_key=True,
        unique=True,
    )
    username = models.CharField(
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        unique=True,
        blank=True,
    )
    password = models.CharField(
        max_length=255,
    )
    is_active = models.BooleanField(
        default=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from .models import UserManager
from django.contrib.auth.forms import UsernameField
from django.core.exceptions import ObjectDoesNotExist
from wordbook.models.quiz import QuizTaker


class SignUpForm(forms.ModelForm):
    class Meta:
        model = UserManager
        fields = ('username', 'email', 'password', )
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': '*Password'}),
        }

    confirm_password = forms.CharField(
        label='確認用パスワード',
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password'}),
    )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {'placeholder': '*Username'}
        self.fields['email'].required = True
        self.fields['email'].widget.attrs = {'placeholder': '*Email'}
        # self.fields['password'].widget.attrs = {'placeholder': 'password'}

    def clean_username(self):
        """usernameのバリデーション"""
        username = self.cleaned_data['username']
        # usernameは3文字以上にならねばエラー表示。
        if len(username) < 3:
            raise forms.ValidationError('Username must be longer than 3')
        # usernameがアルファベットを含んでなければエラー表示。
        if not username.isalpha():
            raise forms.ValidationError('Username must contain alphabets')
        # usernameが数字だけであればエラー表示。
        if username.isnumeric():
            raise forms.ValidationError('Username cannot be only numbers')
        # usernameは数字のみではならない。
        if username.isnumeric():
            raise forms.ValidationError('Username cannot contain only numbers')
        return username

    def clean(self):
        """passwordとconfirm_passwordのバリデーション"""
        super(SignUpForm, self).clean()
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        # password と confirm_passwordが一致していなければエラー表示
        if password != confirm_password:
            raise forms.ValidationError("password and confirmed_password don't match")

    def save(self, commit=True):
        """passwordをハッシュ化してからユーザー情報の保存"""

        user_info = super(SignUpForm, self).save(commit=False)
        user_info.set_password(self.cleaned_data["password"])
        if commit:
            user_info.save()
            QuizTaker.objects.create(user=user_info)

        return user_info


class LogInForm(forms.Form):
    username = UsernameField(
        label='username',
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Username',
                                      'autofocus': True})
    )
    """ -> render_value=True > ログイン画面に戻った際にパスワードが入力された状態のまま。
        -> strip=False > True（Default）の場合、値は先頭と末尾の空白を取り除かれる。"""
    password = forms.CharField(
        label='password',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}, render_value=True)
    )

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        # ユーザー情報を保持する為のオブジェクト生成。
        self.user_request_to_login = None

    def clean_password(self):
        """Validation for password"""
        password = self.cleaned_data['password']
        return password

    def clean_username(self):
        """Validation for username"""
        username = self.cleaned_data['username']
        return username

    def clean(self):
        """Validation username corresponding to its password that was saved in Sign-Up."""
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            requesting_user = UserManager.objects.get(username=username)
        except ObjectDoesNotExist:
            raise forms.ValidationError('Input the correct username. ')
        if not requesting_user.check_password(password):
            raise forms.ValidationError('Input the correct password.')
        self.user_request_to_login = requesting_user

    def get_login_user(self):
        """ユーザ名、データベースIDなどを表す引数 user_id をとり、対応するUserオブジェクトを返す。"""
        return self.user_request_to_login

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from .forms import SignUpForm, LogInForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin


class SignUpView(View):
    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, 'accounts/signup.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if not form.is_valid():
            return render(request, 'accounts/signup.html', {'form': form})
        user_info_save = form.save(commit=True)

        # create_user_blog = Post()
        # create_user_blog.user = user_info_save
        # create_user_blog.save()

        auth_login(request, user_info_save)
        return redirect('accounts:login')


# class ConfirmUserInfo(View):
#     def get(self, request, *args, **kwargs):
#         form = SignUpForm()
#         if not form.is_valid():
#             return render(request, 'accounts/signup.html', {'form': form})
#         return render(request, 'accounts/confirm_user_info.html', {'form': form})


class LogInView(View):
    def get(self, request, *args, **kwargs):
        form = LogInForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = LogInForm(request.POST)
        if not form.is_valid():
            return render(request, 'accounts/login.html', {'form': form})

        login_user = form.get_login_user()
        auth_login(request, login_user)

        return redirect(reverse('wordbook:home'))


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            auth_logout(request)

        return redirect(reverse('accounts:login'))

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block meta_title %}
    SELVOC/SIGN IN
{% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'accounts/login.css' %}">
    <div class="main-w3layouts wrapper">
        <div class="main-agileinfo">
            <h1>SELVOC</h1>
            <h2>LOGIN</h2>
			<div class="agileits-top">
                <form action="" method="post">{% csrf_token %}
                    <form action="" method="get">
                        {% for field in form %}
                            {{ field }}
                            {% if field.errors %}
                                <p>{{ field.errors.0 }}</p>
                            {% endif %}
                        {% endfor %}
                        <input type="submit" value="SIGN IN">
                    </form>
                </form>
                <p>New to SELVOC? <a href="{% url 'accounts:signup' %}"> SignUp now!</a></p>
            </div>
        </div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block meta_title %}
    SELVOC/SIGN UP
{% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'accounts/signup.css' %}">
	<div class="main-w3layouts wrapper">

		<div class="main-agileinfo">
            <h1>SELVOC</h1>

		<h2>SIGN UP</h2>
			<div class="agileits-top">
				<form action="" method="post">{% csrf_token %}
                    <form action="" method="get">
                        {% for field in form %}
                            {{ field }}
                            {% if field.errors %}
                            <p>{{ field.errors.0 }}</p>
                            {% endif %}
                    {% endfor %}
					<input type="submit" value="REGISTER">
                    </form>
				</form>
				<p>Already have an account? <a href="{% url 'accounts:login' %}"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

{% endblock %}