accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('selvoc/accounts/', include('accounts.urls')),
    path('selvoc/wordbook/', include('wordbook.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

wordbook/urls.py
from django.urls import path, re_path
from wordbook.views import quiz, wordbook


app_name = 'wordbook'
urlpatterns = [
    path('home/', wordbook.HomeView.as_view(), name='home'),
    path('home/add_word/', wordbook.WordAddView.as_view(), name='add_word'),
    path('home/delete_word/<int:pk>/', wordbook.WordDeleteView.as_view(), name='delete_word'),
    path('home/quiz_list/', quiz.QuizListView.as_view(), name='quiz_list'),
    path('home/completed_quiz_list/', quiz.CompletedQuizListView.as_view(), name='completed_quiz_list'),
    path('home/quiz_list/quiz_add/', quiz.QuizCreateView.as_view(), name='quiz_add'),
    path('home/quiz_list/game_delete/<int:pk>/', quiz.QuizDeleteView.as_view(), name='quiz_delete'),
    path('home/quiz_list/quiz/<int:pk>/take/', quiz.take_quiz, name='quiz_take'),
    path('home/completed_quiz_list/<int:pk>/delete', quiz.CompletedQuizDeleteView.as_view(), name='completed_quiz_delete')
]

wordbook/views/practicegame.py
import numpy as np
import random

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.utils.decorators import method_decorator

from django.views.generic import CreateView, ListView, UpdateView, FormView, DetailView, DeleteView

from wordbook.models.practicegame import Quiz, QuizTaker, CompletedQuiz, Question, MultipleQuestions
from wordbook.models.wordbook import Wordbook, Word

from django.core.exceptions import ValidationError


from django.core.paginator import Paginator


@method_decorator([login_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'wordbook/quiz_list.html'

    def get_queryset(self):
        login_user = self.request.user.quiztaker
        get_completed_quizzes = login_user.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.exclude(pk__in=get_completed_quizzes).annotate(num_questions=Count('questions'))
        return queryset


@method_decorator([login_required], name='dispatch')
class CompletedQuizListView(ListView):
    model = CompletedQuiz
    context_object_name = 'completed_quizzes'
    template_name = 'wordbook/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.quiztaker.completed_quizzes.select_related('quiz')
        return queryset


@method_decorator([login_required], name='dispatch')
class QuizCreateView(CreateView):
    model = Quiz
    fields = ('name',)
    template_name = 'wordbook/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.taker_id = self.request.user.pk
        quiz.save()
        if Wordbook.objects.filter(user_id=self.request.user.pk).count() < 5:
            messages.error(self.request, "Your wordbook owns less than 5 words. Add more to create a quiz.")
        vocab_list = wordids_random_select(quiz.taker_id)
        for v in vocab_list:
            Question.objects.create(quiz_id=quiz.pk, game_word_id=v['word_id'])
        words_randomly_selected(quiz.pk)
        game_word_ids = Question.objects.filter(quiz_id=quiz.pk).values('game_word', 'pk')
        for gwi in game_word_ids:
            if MultipleQuestions.objects.filter(choices=gwi['game_word']).filter(question=gwi['pk']).exists():
                turn_to_true = MultipleQuestions.objects.filter(choices=gwi['game_word']).filter(question=gwi['pk']).first()
                turn_to_true.is_correct = True
                turn_to_true.save()

        messages.success(self.request, "The quiz '%s' was created with success! Go ahead and take the quiz now!" % quiz)
        return redirect('wordbook:quiz_list')


def wordids_random_select(user_id):
    randomly_selected = np.random.choice(list(Wordbook.objects.filter(user_id=user_id).values('word_id')), 5, replace=False)
    vocab_list = []
    for r in randomly_selected:
        vocab_list.append(r)
    return vocab_list


def words_randomly_selected(get_quiz_id):
    game_wordids = Question.objects.filter(quiz_id=get_quiz_id).values('game_word', 'pk')
    q_id_list = []
    for q_id in game_wordids:
        random_choices = np.random.choice(Word.objects.exclude(pk=q_id['game_word']).values('pk'), 3, replace=False)
        q_id_list.append(random_choices)

    list_for_multiple_choices = []
    for n in range(0, 5):
        for l in q_id_list[n]:
            list_for_multiple_choices.append(l['pk'])

    group_by = 3
    list_divided_by_3 = []
    for l in [list_for_multiple_choices[i:i + group_by] for i in range(0, len(list_for_multiple_choices), group_by)]:
        list_divided_by_3.append(l)

    for n in range(0, 5):
        list_divided_by_3[n][0:0] = [game_wordids[n]['game_word']]

    for ldb3 in list_divided_by_3:
        random.shuffle(ldb3)

    # practice_game_idで絞り込んだ、Questionの id 取得
    list_for_question_ids = []
    for q in game_wordids:
        list_for_question_ids.append(q['pk'])

    # 作成したquestion_idそれぞれに対応するword_idを明確にする為の辞書（combined_dict）を作成
    combined_dict = dict(zip(list_for_question_ids, list_divided_by_3))
    # combined_dictからMultipleChoicesテーブルへ保存
    for cd in combined_dict:
        for n in range(0, 4):
            MultipleQuestions(question_id=cd, choices_id=combined_dict[cd][n]).save()


@method_decorator([login_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Quiz
    success_url = reverse_lazy('wordbook:quiz_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def take_quiz(request):
    return render(request, 'wordbook/take_quiz_form.html')

wordbook/views/quiz.py
import numpy as np
import random

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DeleteView, DetailView

from wordbook.models.quiz import Quiz, CompletedQuiz, Question, MultipleQuestions, QuizTakerAnswer, QuizLength
from wordbook.models.wordbook import Wordbook, Word
from wordbook.forms import QuizTakeForm


@method_decorator([login_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'wordbook/quiz_list.html'

    def get_queryset(self):
        login_user = self.request.user.quiztaker
        get_completed_quizzes = login_user.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.exclude(pk__in=get_completed_quizzes).annotate(num_questions=Count('questions'))
        return queryset


@method_decorator([login_required], name='dispatch')
class CompletedQuizListView(ListView):
    model = CompletedQuiz
    context_object_name = 'completed_quizzes'
    template_name = 'wordbook/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.quiztaker.completed_quizzes.select_related('quiz')
        return queryset


@method_decorator([login_required], name='dispatch')
class QuizCreateView(CreateView):
    model = Quiz
    fields = ('name', 'length')
    template_name = 'wordbook/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.taker_id = self.request.user.pk
        quiz.save()
        quiz_length = get_object_or_404(QuizLength, pk=quiz.length_id)
        if Wordbook.objects.filter(user_id=self.request.user.pk).count() < quiz_length.length:
            messages.error(
                self.request,
                "Your wordbook owns less than %s words. Add more to create a quiz." % str(quiz_length.length)
            )

        vocab_list = wordids_random_select(quiz.taker_id, quiz_length.length)
        for v in vocab_list:
            Question.objects.create(quiz_id=quiz.pk, game_word_id=v['word_id'])
        words_randomly_selected(quiz.pk, quiz_length.length)
        game_word_ids = Question.objects.filter(quiz_id=quiz.pk).values('game_word', 'pk')
        for gwi in game_word_ids:
            if MultipleQuestions.objects.filter(question=gwi['pk']).exists():
                get_vocab_meaning = get_object_or_404(Word, pk=gwi['game_word'])
                turn_to_true = MultipleQuestions.objects.filter(meaning=get_vocab_meaning.vocab_meaning).filter(question=gwi['pk']).first()
                turn_to_true.is_correct = True
                turn_to_true.save()

        messages.success(self.request, "The quiz '%s' was created with success! Go ahead and take the quiz now!" % quiz)
        return redirect('wordbook:quiz_list')


def wordids_random_select(user_id, quiz_length):
    randomly_selected = np.random.choice(list(Wordbook.objects.filter(user_id=user_id).values('word_id')), quiz_length, replace=False)
    vocab_list = []
    for r in randomly_selected:
        vocab_list.append(r)
    return vocab_list


def words_randomly_selected(get_quiz_id, quiz_length):
    game_wordids = Question.objects.filter(quiz_id=get_quiz_id).values('game_word', 'pk')
    q_id_list = []
    for q_id in game_wordids:
        random_choices = np.random.choice(Word.objects.exclude(pk=q_id['game_word']).values('pk'), 3, replace=False)
        q_id_list.append(random_choices)

    list_for_multiple_choices = []
    for n in range(0, quiz_length):
        for l in q_id_list[n]:
            list_for_multiple_choices.append(l['pk'])

    group_by = 3
    list_divided_by_3 = []
    for l in [list_for_multiple_choices[i:i + group_by] for i in range(0, len(list_for_multiple_choices), group_by)]:
        list_divided_by_3.append(l)

    for n in range(0, quiz_length):
        list_divided_by_3[n][0:0] = [game_wordids[n]['game_word']]

    for ldb3 in list_divided_by_3:
        random.shuffle(ldb3)

    # practice_game_idで絞り込んだ、Questionの id 取得
    list_for_question_ids = []
    for q in game_wordids:
        list_for_question_ids.append(q['pk'])

    # 作成したquestion_idそれぞれに対応するword_idを明確にする為の辞書（combined_dict）を作成
    combined_dict = dict(zip(list_for_question_ids, list_divided_by_3))
    # combined_dictからMultipleChoicesテーブルへ保存
    for cd in combined_dict:
        for n in range(0, 4):
            vocab = get_object_or_404(Word, pk=combined_dict[cd][n])
            MultipleQuestions(meaning=vocab.vocab_meaning, question_id=cd).save()


@method_decorator([login_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Quiz
    success_url = reverse_lazy('wordbook:quiz_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


@login_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    login_user = request.user.quiztaker

    if login_user.quizzes.filter(pk=pk).exists():
        return render(request, 'wordbook/taken_quiz_list.html')

    total_questions = quiz.questions.count()
    unanswered_questions = login_user.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()
    # question_list = quiz.questions.values_list('answers__choices__vocab_meaning', flat=True)

    if request.method == 'POST':
        quiz_form = QuizTakeForm(question=question, data=request.POST)
        # question_form = QuizShowForm(data=request.POST)
        if quiz_form.is_valid():
            with transaction.atomic():
                user_answer = quiz_form.save(commit=False)
                # user_answer.is_user_answer = True
                # quiz_taker = QuizTakerAnswer()
                # quiz_taker.taker = login_user
                # quiz_taker.answer = user_answer
                # quiz_taker.save()
                user_answer.taker = login_user
                user_answer.save()
                if login_user.get_unanswered_questions(quiz).exists():
                    return redirect('wordbook:quiz_take', pk)
                else:
                    correct_answers = login_user.quiz_answers.filter(
                        answer__question__quiz=quiz,
                        answer__is_correct=True,
                    ).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    CompletedQuiz.objects.create(user=login_user, quiz=quiz, score=score)
                    if score < 50.0:
                        messages.error(
                            request,
                            'Do better next time! Your score for the quiz %s was %s/100'
                            % (quiz, score),
                        )
                    elif 50 <= score < 80:
                        messages.warning(
                            request,
                            'Better luck next time! Your score for the quiz %s was %s/100.'
                            % (quiz, score),
                        )
                    else:
                        messages.success(
                            request,
                            'Great Job! You completed the quiz %s with a high score, %s/100.'
                            % (quiz, score),
                        )
                    return redirect('wordbook:quiz_list')
    else:
        quiz_form = QuizTakeForm(question=question)
        # question_form = QuizShowForm()

    return render(request, 'wordbook/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'quiz_form': quiz_form,
        'progress': progress,

    })


@method_decorator([login_required], name='dispatch')
class CompletedQuizDetailView(DetailView):
    model = CompletedQuiz

    def get_queryset(self):
        login_user = self.request.user.quiztaker
        queryset = login_user.quiz_answers.filter(pk=login_user)
        return queryset


@method_decorator([login_required], name='dispatch')
class CompletedQuizDeleteView(DeleteView):
    model = CompletedQuiz
    success_url = reverse_lazy('wordbook:completed_quiz_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

# @method_decorator([login_required], name='dispatch')
# class DetailedCompletedQuizView(DetailView):

wordbook/views/wordbook.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic import ListView, FormView, DeleteView
from django.urls import reverse_lazy

from wordbook.forms import WordAddForm
from wordbook.models.wordbook import Wordbook

from django.core.paginator import Paginator

from django.contrib import messages

from bootstrap_modal_forms.mixins import PassRequestMixin


@method_decorator([login_required], name='dispatch')
class HomeView(ListView):
    model = Wordbook
    paginate_by = 12
    template_name = 'wordbook/home.html'

    def get(self, request, *args, **kwargs):
        queryset_list = Wordbook.exec_query(request.user.pk)
        paginator = Paginator(queryset_list, self.paginate_by)

        page = self.request.GET.get('page')

        queryset = paginator.get_page(page)
        context = {
            'queryset': queryset,
        }
        return render(request, 'wordbook/home.html', context)


@method_decorator([login_required], name='dispatch')
class WordAddView(FormView):
    form_class = WordAddForm
    template_name = 'wordbook/word_add.html'
    success_url = reverse_lazy('wordbook:home')

    def get_form_kwargs(self):
        kwargs = super(WordAddView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        form = WordAddForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, 'wordbook/word_add.html', {'form': form})
        form.save(commit=True)
        messages.success(request, "'%s' has been just added" % form.cleaned_data['adding_word'])
        return redirect('wordbook:home')


@method_decorator([login_required], name='dispatch')
class WordDeleteView(DeleteView):
    model = Wordbook
    success_url = reverse_lazy('wordbook:home')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

wordbook/templates/wordbook/_header.html
<h2>Quizzes</h2>
{#<p class="text-muted">#}
{#  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}#}
{#  <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>#}
{#</p>#}

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'wordbook:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'wordbook:completed_quiz_list' %}">Completed</a>
  </li>
</ul>

wordbook/templates/wordbook/home.html
{% extends 'base.html' %}

{% block meta_title %}
    SELVOC/HOME
{% endblock %}
{% block content %}
    {% load i18n %}
{% load static %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'wordbook/home.css' %}">

<head>
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
  <meta charset="utf-8">
  <meta name="add-word" content="width=device-width, initial-scale=1">
</head>

<body style="background: #939393">
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
</body>

    <!-- グローバルナビゲーション -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <h1>SELVOC</h1>
      <h2 style="margin-left: 2%">Home</h2>
    <ul class="navbar-nav mr-auto">
    </ul>
{#      <a class="nav-link" href="{% url 'wordbook:home' %}">Home</a>#}
      <a class="nav-link" href="{% url 'wordbook:add_word' %}">Add</a>
      <a class="nav-link" href="{% url 'wordbook:quiz_list' %}">Practice</a>
      <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
  </div>
</nav>

<div class="modal fade" tabindex="-1" role="form" id="add-word">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        {% include 'wordbook/word_add.html' %}
    </div>
  </div>
</div>


<div style="width: 200px; z-index: 10; position: fixed; right: 4%; bottom: 13%; height: 83px;">
       <a class="fa fa-plus" data-toggle="modal" data-target="#add-word" style="font-size:150px;color:rgb(66,255,134)">
{#                   <i class="fa fa-plus" style="font-size:150px;color:rgb(255,89,133)"></i>#}
       </a>
</div>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".add-word").modalForm({
                formURL: "{% url 'wordbook:add_word' %}"
            });
        });
    </script>



{% if queryset %}
    <form class="col-md-12">
            <table border="3" class="wordbook">
             <thead>
                <tr>
                    <th>単語</th>
                    <th>品詞</th>
                    <th>意味</th>
                    <th></th>
                </tr>
             </thead>
            <tbody>
                {% for entry in queryset %}
                <tr>

                    <td>{{ entry.vocab }}</td>
                    <td>{{ entry.vocab_class }}</td>
                    <td>{{ entry.vocab_meaning }}</td>
{#                    <td>{{ entry.id }}</td>#}
                    <td>
                        <form method="POST" action="{% url 'wordbook:delete_word' entry.id %}">{% csrf_token %}
                             <button type="submit"><i class="fa fa-minus" style="font-size:10px;color:lightseagreen"></i></button>
                        </form>
                    </td>
	        	</tr>
                        {% endfor %}
            </tbody>
            </table>
                {% include 'wordbook/paginate.html' %}
{#    {% include 'wordbook/word_add.html' %}#}
{#                   {% include 'wordbook/word_add.html' %}#}

{##}
{#<div style="width: 200px; z-index: 10; position: fixed; right: 4%; bottom: 13%; height: 83px;">#}
{#   <a class="btn" href="{% url 'wordbook:add_word' %}">#}
{#        <i class="fa fa-plus" style="font-size:150px;color:rgb(251,244,255)"></i></a>#}
{#</div>#}
{#    <div style="width: 200px; z-index: 10; position: fixed; right: 4%; bottom: 13%; height: 83px;">#}
{#   #}
{#    </div>#}

    </form>
{% else %}
            <p>{% trans "No Word Registered. Register One Now!" %}.</p>
{% endif %}

{% endblock %}

wordbook/templates/wordbook/quiz_list.html
{% extends 'base.html' %}

{% block content %}
        {% load static %}
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" media="all" href="{% static 'wordbook/home.css' %}">
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- グローバルナビゲーション -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <h1>SELVOC</h1>
      <h2 style="margin-left: 2%">Practice</h2>
    <ul class="navbar-nav mr-auto">
    </ul>
      <a class="nav-link" href="{% url 'wordbook:home' %}">Home</a>

      <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
  </div>
</nav>

        {% include 'wordbook/_header.html' with active='new' %}
        <form method="POST" action="{% url 'wordbook:quiz_add' %}">{% csrf_token %}
      <button type="submit" class="btn btn-success">クイズ作成</button>
     </form>
{#  <div class="card">#}
    <table class="table mb-0">
      <thead>
        <tr>
          <th class="text-center">Quiz</th>
{#          <th>Subject</th>#}
          <th class="text-center">Length</th>
          <th class="text-center"></th>
            <th class="text-center"></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="text-center">{{ quiz.name }}</td>
{#            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>#}
            <td class="text-center">{{ quiz.num_questions }} questions</td>
            <td class="text-center">
              <a href="{% url 'wordbook:quiz_take' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          <td class="text-center"><a href="{% url 'wordbook:quiz_delete' quiz.pk %}"><button type="button" class="btn btn-primary remove-btn">
      <i class="fa fa-minus" aria-hidden="true"></i>
    </button></a></td>
          </tr>
{# {% for q in queryset %}#}
{#          <tr>#}
{#            <td class="align-middle">{{ q.name }}</td>#}
{#            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>#}
{#            <td class="align-middle">{{ q.questions_count }} questions</td>#}
{#            <td class="text-right">#}
{#              <a href="{% url 'wordbook:game_play' q.pk %}" class="btn btn-primary">Start quiz</a>#}
{#            </td>#}
{#          <td class="text-right"><a href="{% url 'wordbook:delete_word' q.id %}">Delete</a></td>#}
{#          </tr>#}
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz registered yet.</td>
          </tr>
        {% endfor %}
{#      </tbody>#}
{#    </table>#}
{#    {% include 'wordbook/paginate.html' %}#}
{#  </div>#}
      </tbody>
    </table>
{% endblock %}

wordbook/templates/wordbook/taken_quiz_list.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" media="all" href="{% static 'wordbook/home.css' %}">
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- グローバルナビゲーション -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <h1>SELVOC</h1>
      <h2 style="margin-left: 2%">Practice</h2>
    <ul class="navbar-nav mr-auto">
    </ul>
      <a class="nav-link" href="{% url 'wordbook:home' %}">Home</a>

      <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
  </div>
</nav>
  {% include 'wordbook/_header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th class="text-center">Quiz</th>
{#          <th>Subject</th>#}
          <th class="text-center">Score</th>
            <th class="text-center">Accumulated Average Score</th>
          <th class="text-center"></th>
        </tr>
      </thead>
      <tbody>
        {% for completed_quiz in completed_quizzes %}
          <tr>
            <td class="text-center">{{ completed_quiz.quiz.name }}</td>
{#            <td>{{ taken_quiz.quiz.subject.get_html_badge }}</td>#}
            <td class="text-center">{{ completed_quiz.score }}/100</td>
              <td class="text-center"></td>
            <td class="text-center"><a href="{% url 'wordbook:completed_quiz_delete' completed_quiz.pk %}"><button type="button" class="btn btn-primary remove-btn">
      <i class="fa fa-minus" aria-hidden="true"></i>
    </button></a></td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}